import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// Generated from the directory, so a page added to `sync-docs.mjs` appears
// here without a second list to keep in step; order comes from each page's
// `sidebar_position`.
const sidebars: SidebarsConfig = {
  docs: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
