#!/bin/sh
# The release workflows must parse, and the strings that hold them together
# must stay: the patches scripts/dist-generate.sh makes to the generated
# release.yml, the two entry points that dispatch it, and the title contract
# between release-plz.toml, release-plz.yml and cliff.toml.
set -eu

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
wf="$ROOT/.github/workflows"

command -v ruby >/dev/null 2>&1 \
    || { echo "release-workflows: ruby is required to parse the workflows" >&2; exit 1; }
for f in release bump release-plz verify tap; do
    [ -f "$wf/$f.yml" ] || { echo "release-workflows: missing $wf/$f.yml" >&2; exit 1; }
    ruby -ryaml -e "YAML.load_file(ARGV[0])" "$wf/$f.yml"
done

need() {
    if ! grep -q -- "$2" "$1"; then
        echo "release-workflows: $(basename "$1") is missing $3" >&2
        exit 1
    fi
}

r="$wf/release.yml"
need "$r" 'autogenerated by dist' 'the dist header (regenerate with `just dist-generate`)'
need "$r" 'CODESIGN_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}' 'the MACOS_CERTIFICATE mapping'
need "$r" 'CODESIGN_CERTIFICATE_PASSWORD: ${{ secrets.MACOS_CERTIFICATE_PWD }}' 'the MACOS_CERTIFICATE_PWD mapping'
need "$r" 'Discover macOS codesign identity' 'the identity step from .github/build-setup.yml'
need "$r" 'name: Notarise' 'the Notarise step from .github/build-check.yml'
need "$r" "vars.KETCH_NOTARIZE == 'true'" 'the KETCH_NOTARIZE gate'
need "$r" 'secrets.APPSTORE_CONNECT_KEY }}' 'APPSTORE_CONNECT_KEY'
need "$r" 'secrets.APPSTORE_CONNECT_KEY_ID' 'APPSTORE_CONNECT_KEY_ID'
need "$r" 'secrets.APPSTORE_CONNECT_ISSUER_ID' 'APPSTORE_CONNECT_ISSUER_ID'
need "$r" 'xcrun notarytool submit' 'notarytool submit'
need "$r" 'source=Notarized Developer ID' 'the spctl smoke check'
need "$r" 'name: Smoke test' 'the smoke test'
need "$r" 'sha256sum $(ls ketch-\*.tar.gz | sort) > SHA256SUMS' 'the aggregate SHA256SUMS'
need "$r" 'uses: ./.github/workflows/tap.yml' 'the tap publish job'

b="$wf/bump.yml"
need "$b" 'options: \[patch, minor, major\]' 'the patch/minor/major choice'
need "$b" 'uses: ./.github/workflows/verify.yml' 'the verify gate'
need "$b" 'scripts/release.sh "$LEVEL"' 'the release.sh call'

p="$wf/release-plz.yml"
need "$p" "grep -qE '^chore: release v" 'the merge gate'
need "$p" 'startswith("release-plz-")' 'the release-plz branch check'
need "$p" 'uses: ./.github/workflows/verify.yml' 'the verify gate'
need "$p" 'scripts/release.sh patch --no-bump' 'the --no-bump dispatch'

need "$ROOT/release-plz.toml" 'pr_name = "chore: release v{{ version }}"' 'the pull request title the gate matches'
need "$ROOT/release-plz.toml" 'changelog_config = "cliff.toml"' 'the shared git-cliff config'
need "$ROOT/cliff.toml" 'message = "^chore: release v", skip = true' 'the skipped version commit'
need "$ROOT/scripts/release.sh" 'git commit --quiet -m "chore: release v$version"' 'the version commit subject'
